name: winbuild CI

on:
  push:
    branches: [ "msvc-cmake" ]
  pull_request:
    branches: [ "msvc-cmake" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
          - amd64_arm64
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: '2022'
      - name: Set up Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: build libcurl
        run: call "%GITHUB_WORKSPACE%\winbuild\build.bat" curl
        shell: cmd

      - name: build
        run: call "%GITHUB_WORKSPACE%\winbuild\build.bat" trurl
        shell: cmd

      - name: test
        run: call "%GITHUB_WORKSPACE%\winbuild\build.bat" test
        shell: cmd
