name: winbuild CI

on:
  push:
    branches: [ "msvc-cmake" ]
  pull_request:
    branches: [ "msvc-cmake" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TYPE: [debug, release]
    env:
      CURL_VER: 8.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libc6-dev zlib1g-dev libssl-dev libidn2-dev libldap-dev
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build libcurl
        run: bash "$GITHUB_WORKSPACE/winbuild/build.sh" curl "" ${{matrix.BUILD_TYPE}} $CURL_VER
        shell: bash

      - name: Build trurl
        run: bash "$GITHUB_WORKSPACE/winbuild/build.sh" trurl "" ${{matrix.BUILD_TYPE}} $CURL_VER
        shell: bash

      - name: Test trurl
        run: bash "$GITHUB_WORKSPACE/winbuild/build.sh" test "" ${{matrix.BUILD_TYPE}} $CURL_VER
        shell: bash

  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
        BUILD_TYPE: [debug, release]
    env:
      CURL_VER: 8.0.1
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: '2022'

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build libcurl
        run: call "%GITHUB_WORKSPACE%\winbuild\build.bat" curl "" ${{matrix.BUILD_TYPE}} %CURL_VER%
        shell: cmd

      - name: Build trurl
        run: call "%GITHUB_WORKSPACE%\winbuild\build.bat" trurl "" ${{matrix.BUILD_TYPE}} %CURL_VER%
        shell: cmd

      - name: Test trurl
        run: call "%GITHUB_WORKSPACE%\winbuild\build.bat" test "" ${{matrix.BUILD_TYPE}} %CURL_VER%
        shell: cmd
